services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14-rootless
    container_name: forgejo
    user: "1000:1000"
    restart: "no"
    environment:
      USER_UID: "1000"
      USER_GID: "1000"
    ports:
      - "3000:3000"
      - "2222:2222"
    volumes:
      - ${HOME}/.local/share/forgejo-dev:/var/lib/gitea
      - /etc/localtime:/etc/localtime:ro
